# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import robot_control_pb2 as robot__control__pb2


class RobotServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ControlAuger = channel.unary_unary(
                '/robot.RobotService/ControlAuger',
                request_serializer=robot__control__pb2.SequenceCommandRequest.SerializeToString,
                response_deserializer=robot__control__pb2.SequenceStatusResponse.FromString,
                )
        self.ControlPlanter = channel.unary_unary(
                '/robot.RobotService/ControlPlanter',
                request_serializer=robot__control__pb2.SequenceCommandRequest.SerializeToString,
                response_deserializer=robot__control__pb2.SequenceStatusResponse.FromString,
                )
        self.ControlBoth = channel.unary_unary(
                '/robot.RobotService/ControlBoth',
                request_serializer=robot__control__pb2.SequenceCommandRequest.SerializeToString,
                response_deserializer=robot__control__pb2.SequenceStatusResponse.FromString,
                )
        self.MachineCommand = channel.unary_unary(
                '/robot.RobotService/MachineCommand',
                request_serializer=robot__control__pb2.MachineCommandRequest.SerializeToString,
                response_deserializer=robot__control__pb2.MachineStatusResponse.FromString,
                )
        self.GetMachineStatus = channel.unary_unary(
                '/robot.RobotService/GetMachineStatus',
                request_serializer=robot__control__pb2.Empty.SerializeToString,
                response_deserializer=robot__control__pb2.MachineStatusResponse.FromString,
                )
        self.GetSequenceDetail = channel.unary_unary(
                '/robot.RobotService/GetSequenceDetail',
                request_serializer=robot__control__pb2.Empty.SerializeToString,
                response_deserializer=robot__control__pb2.SequenceDetailResponse.FromString,
                )
        self.ControlRobot = channel.unary_unary(
                '/robot.RobotService/ControlRobot',
                request_serializer=robot__control__pb2.MachineCommandRequest.SerializeToString,
                response_deserializer=robot__control__pb2.MachineStatusResponse.FromString,
                )
        self.GetAugerMotorStatus = channel.unary_unary(
                '/robot.RobotService/GetAugerMotorStatus',
                request_serializer=robot__control__pb2.Empty.SerializeToString,
                response_deserializer=robot__control__pb2.AugerMotorStatusResponse.FromString,
                )


class RobotServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ControlAuger(self, request, context):
        """── Sequence control ───────────────────────────────────────────────────────
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ControlPlanter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ControlBoth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MachineCommand(self, request, context):
        """── Machine-level pushbutton commands ─────────────────────────────────────
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMachineStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSequenceDetail(self, request, context):
        """── Full sequence state readback ───────────────────────────────────────────
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ControlRobot(self, request, context):
        """── Robot arm control ──────────────────────────────────────────────────────
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAugerMotorStatus(self, request, context):
        """── Auger motor status ────────────────────────────────────────────────────
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RobotServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ControlAuger': grpc.unary_unary_rpc_method_handler(
                    servicer.ControlAuger,
                    request_deserializer=robot__control__pb2.SequenceCommandRequest.FromString,
                    response_serializer=robot__control__pb2.SequenceStatusResponse.SerializeToString,
            ),
            'ControlPlanter': grpc.unary_unary_rpc_method_handler(
                    servicer.ControlPlanter,
                    request_deserializer=robot__control__pb2.SequenceCommandRequest.FromString,
                    response_serializer=robot__control__pb2.SequenceStatusResponse.SerializeToString,
            ),
            'ControlBoth': grpc.unary_unary_rpc_method_handler(
                    servicer.ControlBoth,
                    request_deserializer=robot__control__pb2.SequenceCommandRequest.FromString,
                    response_serializer=robot__control__pb2.SequenceStatusResponse.SerializeToString,
            ),
            'MachineCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.MachineCommand,
                    request_deserializer=robot__control__pb2.MachineCommandRequest.FromString,
                    response_serializer=robot__control__pb2.MachineStatusResponse.SerializeToString,
            ),
            'GetMachineStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMachineStatus,
                    request_deserializer=robot__control__pb2.Empty.FromString,
                    response_serializer=robot__control__pb2.MachineStatusResponse.SerializeToString,
            ),
            'GetSequenceDetail': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSequenceDetail,
                    request_deserializer=robot__control__pb2.Empty.FromString,
                    response_serializer=robot__control__pb2.SequenceDetailResponse.SerializeToString,
            ),
            'ControlRobot': grpc.unary_unary_rpc_method_handler(
                    servicer.ControlRobot,
                    request_deserializer=robot__control__pb2.MachineCommandRequest.FromString,
                    response_serializer=robot__control__pb2.MachineStatusResponse.SerializeToString,
            ),
            'GetAugerMotorStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAugerMotorStatus,
                    request_deserializer=robot__control__pb2.Empty.FromString,
                    response_serializer=robot__control__pb2.AugerMotorStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'robot.RobotService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RobotService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ControlAuger(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/robot.RobotService/ControlAuger',
            robot__control__pb2.SequenceCommandRequest.SerializeToString,
            robot__control__pb2.SequenceStatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ControlPlanter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/robot.RobotService/ControlPlanter',
            robot__control__pb2.SequenceCommandRequest.SerializeToString,
            robot__control__pb2.SequenceStatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ControlBoth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/robot.RobotService/ControlBoth',
            robot__control__pb2.SequenceCommandRequest.SerializeToString,
            robot__control__pb2.SequenceStatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MachineCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/robot.RobotService/MachineCommand',
            robot__control__pb2.MachineCommandRequest.SerializeToString,
            robot__control__pb2.MachineStatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMachineStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/robot.RobotService/GetMachineStatus',
            robot__control__pb2.Empty.SerializeToString,
            robot__control__pb2.MachineStatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSequenceDetail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/robot.RobotService/GetSequenceDetail',
            robot__control__pb2.Empty.SerializeToString,
            robot__control__pb2.SequenceDetailResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ControlRobot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/robot.RobotService/ControlRobot',
            robot__control__pb2.MachineCommandRequest.SerializeToString,
            robot__control__pb2.MachineStatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAugerMotorStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/robot.RobotService/GetAugerMotorStatus',
            robot__control__pb2.Empty.SerializeToString,
            robot__control__pb2.AugerMotorStatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
